## NUMPY ##
*** .numpy is used for numerical calculations 
    .numpy works with the arrays not with list because arrays work faster
    .***

In [ ]:
import numpy as np

In [ ]:
l=[100,200,300,400,500]
[x+50 for x in l] #applying loop for increasing the bonus to 50

[150, 250, 350, 450, 550]

In [ ]:
l=[10,20,30,40,50]
type(l)
l[0]=100 #replace ()
print(l) 
l.append(60)
print(l)



[100, 20, 30, 40, 50]
[100, 20, 30, 40, 50, 60]


In [ ]:
lst=[1,2,3,4]
a1=np.array(lst) #for converting list to array
a1
type(a1)

numpy.ndarray

In [ ]:
list1=[10,2,3.5,7,'np','6j']
a2=np.array(list1) #for converting list to array
type(a2)
print(a2)
# Arrays are homogeneous it cannot store diferent type of data

['10' '2' '3.5' '7' 'np' '6j']


In [ ]:
l1=[10,20,30,40,50]
l2=[1,2,3,4,5]
print(l1+l2) #list can concatenate whereas numpy cannot below ex

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]


In [ ]:
arr1=np.array(l1)
arr2=np.array(l2)
print(arr1+arr2)


#numpy works faster with array not with list 

[11 22 33 44 55]


In [ ]:
arr3=np.array([10,2,5,60,40,80])
print(arr3)


[10  2  5 60 40 80]


In [ ]:
#arr2+arr3 ValueError: operands could not be broadcast together with shapes (5,) (6,) 
# '''only same sized array can be used'''

In [ ]:
arr4=np.array([[10,20],[30,40],[50,60]]) #dimensions 
print(arr4)

[[10 20]
 [30 40]
 [50 60]]


In [ ]:
arr4.ndim #it display the dimension

2

In [ ]:
arr4.shape #no of rows and cols

(3, 2)

In [ ]:
arr4.size #displays no of counts

6

In [ ]:
arr4.itemsize #returns memory size(bytes) of the each item i.e,8bytes

8

In [ ]:
arr4.nbytes 
#returns memory size(bytes) of all the items in array

48