In [1]:
import numpy as np

In [2]:
r=range(0,100,2)
a=np.array(r) 
a     #converting range into array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [3]:
np.arange(0,100,2) #we can use arange fn to avoid converting range to array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [4]:
np.linspace(0,10) #divides the no in to equal parts
np.linspace(0,10,num=5)
np.linspace(0,10,num=5,retstep=True) #shows the difference 
np.linspace(0,10,num=5,retstep=True,endpoint=False)

(array([0., 2., 4., 6., 8.]), np.float64(2.0))

In [5]:
#used for creating num of rows and cols only with 0's matrix
np.zeros(2)
np.zeros((2,3)) 
np.zeros((2,3,4)) 

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [6]:
# used for creating num of rows and cols only with 1's by matrix
np.ones(2)
np.ones((2,3))
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [7]:
# eye will generate always square matrix i,e identity matrix (diagonal=1)
np.eye(3)
np.eye(4,5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [8]:
np.full(5,5) #syn:np.full(size,element)
np.full((2,4),100) #2 rows 4 cols with value 100

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

In [9]:
#module random is used to generate random num
import numpy.random as rd

In [10]:
# used random integer values within the range of 2
rd.randint(2)

1

In [11]:
rd.randint(10,100) #range between 10-100
rd.randint(10,100,(3)) #it will create in the form matrix with 3 rows
rd.randint(10,100,(3,2)) #it will create in the form matrix with 3rows and 2cols

array([[98, 36],
       [85, 18],
       [12, 43]], dtype=int32)

In [12]:
#seed is used to fix the array without changing whenever we run
rd.seed(2)
rd.randint(10,100,(3,2)) # output:array([[50, 25],[82, 32],[53, 92]], dtype=int32)
print(rd.randint(10,100,(3,2))) #print fun is used to avoid dtype
       

[[85 17]
 [44 59]
 [85 95]]


In [13]:
rd.rand(3) #it gives floating values between 0-1 and only takes size
rd.rand(2,3)

array([[0.81822672, 0.68302599, 0.49856117],
       [0.58679698, 0.71975423, 0.25849809]])

In [14]:
r=rd.randn(2)
print(r)

print(np.mean(r))
print(np.std(r))

[-2.24587483  1.11957525]
-0.5631497905172993
1.6827250392436395


In [15]:
r=rd.randn(2,3)
print(r)

np.mean(r)
np.std(r)

[[-1.054368   -1.0088915  -0.06752199]
 [-0.08142505  2.83521598 -0.24617517]]


np.float64(1.3048708580404422)

In [16]:
#choice method
l=[10,20,30,40,50]
rd.choice(l,3) #it will choose the anyone num from l


array([50, 30, 20])

In [17]:
rd.choice(l,3,replace=False) #use replace to avoid repetition of num


array([40, 50, 20])

In [18]:
l=[10,20,30,40,50]
rd.choice(l,(2,3)) #it will create 2rows and 3 cols

array([[20, 10, 20],
       [10, 30, 20]])

In [19]:
col=['purple','red','yellow','maroon','pink','green','blue','white']
rd.choice(col,3,replace=False,p=[0.17,0.1,0.12,0,0,0.11,0.5,0]) #no of 



array(['purple', 'blue', 'yellow'], dtype='<U6')