## BRODCASTING ##

In [1]:
import numpy as np

In [2]:
l1=[1,2,3,5]
a1=np.array(l1)
print(a1.shape)
c=100

(4,)


In [3]:
a1+c

array([101, 102, 103, 105])

In [4]:
l2=[1,2,3,4]
a2=np.array(l2)
print(a2.shape)
c=100

(4,)


In [5]:
a1+a2

array([2, 4, 6, 9])

In [6]:
a3=np.array([100,200,300,400])

In [7]:
a2+a3

array([101, 202, 303, 404])

In [8]:

a4=np.array([100,200,300,400])
print(a4)
print(a4.shape)


[100 200 300 400]
(4,)


In [9]:
a1+a4

array([101, 202, 303, 405])

In [10]:
a5=np.array([[[8],[5]],[[2],[1]],[[23],[36]]])
print(a5)
print(a5.shape)

[[[ 8]
  [ 5]]

 [[ 2]
  [ 1]]

 [[23]
  [36]]]
(3, 2, 1)


In [11]:
a4+a5

array([[[108, 208, 308, 408],
        [105, 205, 305, 405]],

       [[102, 202, 302, 402],
        [101, 201, 301, 401]],

       [[123, 223, 323, 423],
        [136, 236, 336, 436]]])