In [1]:
import numpy as np

In [2]:
a1=np.arange(10,96,5)
print(a1)
print(a1.shape)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)


In [3]:
#reshape is used to convert one type of shape to other 
np.reshape(a1,shape=(2,9))


array([[10, 15, 20, 25, 30, 35, 40, 45, 50],
       [55, 60, 65, 70, 75, 80, 85, 90, 95]])

In [4]:
np.reshape(a1,(3,6))

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [5]:
a2=np.reshape(a1,(3,2,3))
print(a2)

[[[10 15 20]
  [25 30 35]]

 [[40 45 50]
  [55 60 65]]

 [[70 75 80]
  [85 90 95]]]


In [6]:
np.reshape(a2,(-1))

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [7]:
a3=np.array([[10,20,30,40,50,78],[2,4,5,60,64,28],[11,9,37,92,55,68]])
print(a3)
print(a3.shape)
print(a3.ndim,a3.size,sep='\n')

[[10 20 30 40 50 78]
 [ 2  4  5 60 64 28]
 [11  9 37 92 55 68]]
(3, 6)
2
18


In [8]:
np.reshape(a3,(3,2,1,3))
np.reshape(a3,(3,3,2))



array([[[10, 20],
        [30, 40],
        [50, 78]],

       [[ 2,  4],
        [ 5, 60],
        [64, 28]],

       [[11,  9],
        [37, 92],
        [55, 68]]])