In [ ]:
import numpy as np

In [ ]:
a1=np.array([10,20,30])
print(a1)

[10 20 30]


In [ ]:
np.power(a1,2) # squares the values 

array([100, 400, 900])

In [ ]:
np.sum(a1) #adds the elements in array

np.int64(60)

In [ ]:
np.std(a1) #standard deviation values of array

np.float64(8.16496580927726)

In [ ]:
np.mean(a1) #average values of array

np.float64(20.0)

In [ ]:
np.var(a1) #used to check the how far/near the value is from mean value

np.float64(66.66666666666667)

In [ ]:
a2=np.array([1,0,2])

In [ ]:
np.exp(a2) #exponential of the a2 e gives the power fn

array([2.71828183, 1.        , 7.3890561 ])

In [ ]:
np.log(a2) #retrives the value of that power

C:\Users\USER\AppData\Local\Temp\ipykernel_2300\4191117931.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a2) #retrives the value of that power


array([0.        ,       -inf, 0.69314718])

In [ ]:
a3=np.array([2.71828183, 1.        , 7.3890561 ])
np.log(a3)

array([1., 0., 2.])

In [ ]:
arr1=np.array([10,2,15,5,9,20])
print(arr1)

[10  2 15  5  9 20]


In [ ]:
20 in arr1


True

In [ ]:
np.isin(20,arr1)

array(True)

In [ ]:
np.isin([2,15,8,20],arr1)

array([ True,  True, False,  True])

In [ ]:
np.sort(arr1)

array([ 2,  5,  9, 10, 15, 20])

In [ ]:
np.median(arr1)

np.float64(9.5)

In [ ]:
np.percentile(arr1,25)
np.percentile(arr1,50)
np.percentile(arr1,75)
np.percentile(arr1,100)

np.float64(20.0)

In [ ]:
arr1[np.where(arr1<11)]

array([15, 20])