In [1]:
import numpy as np

In [2]:
a1=np.array([10,20,30])
print(a1)

[10 20 30]


In [3]:
#Copy method (it is independent method)
s_a=np.copy(a1)
print(s_a)
s_a[0]=100
print(s_a)
print(a1)

[10 20 30]
[100  20  30]
[10 20 30]


In [4]:
#veiw is dependent and stored in same memory location  
a3=a1.view() 
print('a3:',a3)
print('a3:',a3)

a3[-1]=200
print('a3:',a3)
print('a1:',a1)

a3: [10 20 30]
a3: [10 20 30]
a3: [ 10  20 200]
a1: [ 10  20 200]
