In [1]:
import numpy as np

In [2]:
a1=np.array([[1,2,3],[10,20,30]])
print(a1)

[[ 1  2  3]
 [10 20 30]]


In [3]:
np.reshape(a1,(-1))

array([ 1,  2,  3, 10, 20, 30])

In [4]:
#ravel function behaves like view method 
# it is going to update the original array also
x=a1.ravel() #->it is coverting in to 1d array
print(x)
x[0]=50
print(a1,x,sep='\n')

[ 1  2  3 10 20 30]
[[50  2  3]
 [10 20 30]]
[50  2  3 10 20 30]


In [5]:
a4=np.array([[11,22,33],[4,67,80]])
print(a4)

[[11 22 33]
 [ 4 67 80]]


In [6]:
#flatten it is coverting in to 1d array
#it is independent it doesnt update the original array
y=a4.flatten() 
print(y)

y[-1]=900
print(a4,y,sep='\n')

[11 22 33  4 67 80]
[[11 22 33]
 [ 4 67 80]]
[ 11  22  33   4  67 900]
